<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Not you_u_0_4_1q</name>
   <tag></tag>
   <elementGuidId>62817860-36f0-485e-b2be-f9f049ccdd0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#u_0_4_1q</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='u_0_4_1q']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9ccadea5-cb97-4ef6-9142-a9f288fca5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9lsb _9ls8</value>
      <webElementGuid>8b006b58-25bc-4431-aaa5-e0ae0d878c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_0_4_1q</value>
      <webElementGuid>2e62417e-d3cf-4740-9185-3645b11e392c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_0_4_1q&quot;)</value>
      <webElementGuid>c6427506-9cf0-4324-8b18-1f6943ff1596</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='u_0_4_1q']</value>
      <webElementGuid>f97026b7-48ba-4c49-a317-c8258fa9fac0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_0_3_os']/a/div/div</value>
      <webElementGuid>5889e5fd-0442-4643-8791-959fa9809d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div/div</value>
      <webElementGuid>6da841dc-0efb-4f23-8e68-fc6b63b89d95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'u_0_4_1q']</value>
      <webElementGuid>f4f9c3f7-1a70-46ad-b8f8-2a1e7fc89e88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
