<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please check your emails for a messag_fc2a23</name>
   <tag></tag>
   <elementGuidId>4795696e-5a47-460e-aa12-0a861f0156c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='recovery_code_entry']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#recovery_code_entry</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>348d4496-8828-4c57-b1d7-c8e3d82bc599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ffd053c2-e5ec-41cd-a8de-84f40a89f318</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputtext _9o1w _9o1_</value>
      <webElementGuid>8262adea-1126-40ba-a855-2fdce9fc6049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>n</value>
      <webElementGuid>64bfea94-245c-4da2-a8b7-c14f3df8bfd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recovery_code_entry</value>
      <webElementGuid>1ad9225c-d63c-494f-b75b-1b6c0d7590e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter code</value>
      <webElementGuid>75f30800-158d-4fff-acca-df15e5fad588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8c126a65-0efc-4da4-bd2d-d2e30c8c9141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter code</value>
      <webElementGuid>ba433f17-909d-4287-9ed2-a2dd29d4166f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recovery_code_entry&quot;)</value>
      <webElementGuid>41959bd3-ce98-440e-a893-3d546492fa70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='recovery_code_entry']</value>
      <webElementGuid>17095b5e-8230-4355-9efe-b05afa2451f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_2_o2']/div/div[2]/div[3]/div/input</value>
      <webElementGuid>bc4249cc-d775-4563-bf9e-48a3fe83987b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>97acfbc0-f4c6-4b87-aa60-226a6bfb2f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'n' and @id = 'recovery_code_entry' and @placeholder = 'Enter code']</value>
      <webElementGuid>74e3c236-40ac-4ae4-aeef-0fa6bb85e3d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
