<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please check your emails for a messag_6d8c97</name>
   <tag></tag>
   <elementGuidId>e65390a4-efed-4b88-81f5-523f287d9b9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#recovery_code_entry</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='recovery_code_entry']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3c501b0-74a4-4248-8739-72a7d0980450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7d40e000-d6d6-403b-9822-5cad427150bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputtext _9o1w _9o1_</value>
      <webElementGuid>63ee4beb-eb84-4519-8f2a-194f61ff8902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>n</value>
      <webElementGuid>ae1199a7-99a9-44c6-82d0-d6ca4cb7d37f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>recovery_code_entry</value>
      <webElementGuid>e5fc06d9-8b64-4ca2-b209-2497d811bcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter code</value>
      <webElementGuid>f7ca8f41-638e-418a-aedc-40a08f6519e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>fca5fa93-d03f-4a3e-9b9f-c392c159102a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Enter code</value>
      <webElementGuid>4c2a0924-9232-42bd-b7e4-2407843eba40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;recovery_code_entry&quot;)</value>
      <webElementGuid>e0ecdac1-e5ee-42e1-bfa1-95d66006800c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='recovery_code_entry']</value>
      <webElementGuid>ba87c615-13d9-411b-af39-125773356a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_2_Dd']/div/div[2]/div[3]/div/input</value>
      <webElementGuid>26d33227-e088-4086-b7f7-ed6170c28aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>349abf33-d726-4674-af4f-32b9ba66d940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'n' and @id = 'recovery_code_entry' and @placeholder = 'Enter code']</value>
      <webElementGuid>057f012f-ba94-45c8-8a0d-1ffacf118857</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
