<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Choose a new password_password_new</name>
   <tag></tag>
   <elementGuidId>52994116-f978-41ce-851c-9d94e9ec5c6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password_new</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password_new']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88771209-c2d8-45da-8cb6-859f3270fc63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2a42e332-c07a-4d93-9918-0dcdea8dcc8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputtext _55r1 _9oku _9o1w</value>
      <webElementGuid>b7247a1a-d413-4e53-826f-f2e420f4b335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password_new</value>
      <webElementGuid>88d7957e-9d7c-493a-8b41-e1e9fd221e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password_new</value>
      <webElementGuid>99e4a826-4453-4bb5-8f3b-0c88984413a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>New password</value>
      <webElementGuid>cccc30b6-77cc-4537-8357-e2a2c362cea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a1bb076b-8dc9-4580-a470-1c79b4ae90bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>New password</value>
      <webElementGuid>ff03e4da-7a02-4cfe-ad60-357b4e43de5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password_new&quot;)</value>
      <webElementGuid>08d5a1aa-e97e-4353-8336-19bdfb27b222</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password_new']</value>
      <webElementGuid>cb84240e-0208-4c1c-a6a6-1c1343f155ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='u_0_2_Ld']/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>ec8175d5-f0ea-4166-9a1b-add3e1baae31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>1d12cb9b-79c9-4f8d-ae98-bba3a47bf7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'password_new' and @name = 'password_new' and @placeholder = 'New password']</value>
      <webElementGuid>a0f0bbe1-8980-4052-b106-96b0a740942b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
