<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Log In with Google</name>
   <tag></tag>
   <elementGuidId>aa344659-643a-4798-8819-1d2df954a46f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='loginform']/div[4]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a._42ft._4jy0._82go._4jy6._517h._51sy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d01a1ded-2cd1-47f1-8e8c-8489a2f4b8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>464ba8fd-5403-43b9-9c43-b8048f4a1a13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _4jy0 _82go _4jy6 _517h _51sy</value>
      <webElementGuid>c5dc8b19-7d2d-4a63-840f-677ca3c52f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://accounts.google.com/o/oauth2/auth?client_id=15057814354-80cg059cn49j6kmhhkjam4b00on1gb2n.apps.googleusercontent.com&amp;state=ARe7JzeWUeTehscE4lSMv5KS0pcyExxSOnZN25xKSERrW8pN3swIy4ROGEpYGUgS2cnCIgTSQkz-mGV_yO5Rf63FtRqePo6X6M58uDmCJK1r8ClPhv_geqgLB9y_RbS-QN7AuhJ00QwDQlbg1jojqegE9aue62e3JI91zq4jAir781qlj6_hZDMYTeEQXc4hCWU9fUq-Fp5H-qpAW4ft8SDruDzZpNxfF0pX2Gx_oRpHIxBQlEUZFXyFpgB-bhCSAz7CoafmDRaceurZy145EhVD&amp;response_type=code&amp;redirect_uri=https%3A%2F%2Fwww.facebook.com%2Foauth2%2Fredirect%2F&amp;scope=openid+email&amp;login_hint=melliaafifah15%40gmail.com</value>
      <webElementGuid>a4c2d069-791e-46e4-8318-777f5cba535f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fc24a46b-f0f7-49ca-841e-1153bbed4e6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>41dd1126-3e75-4339-a8b2-9d7bd9ef8d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener nofollow</value>
      <webElementGuid>2813b7e5-5bf1-43a6-a889-2f3f8b712ce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lynx-mode</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>54bd11e9-6677-45a4-900f-553d0d8a8709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-lynx-uri</name>
      <type>Main</type>
      <value>https://l.facebook.com/l.php?u=https%3A%2F%2Faccounts.google.com%2Fo%2Foauth2%2Fauth%3Fclient_id%3D15057814354-80cg059cn49j6kmhhkjam4b00on1gb2n.apps.googleusercontent.com%26state%3DARe7JzeWUeTehscE4lSMv5KS0pcyExxSOnZN25xKSERrW8pN3swIy4ROGEpYGUgS2cnCIgTSQkz-mGV_yO5Rf63FtRqePo6X6M58uDmCJK1r8ClPhv_geqgLB9y_RbS-QN7AuhJ00QwDQlbg1jojqegE9aue62e3JI91zq4jAir781qlj6_hZDMYTeEQXc4hCWU9fUq-Fp5H-qpAW4ft8SDruDzZpNxfF0pX2Gx_oRpHIxBQlEUZFXyFpgB-bhCSAz7CoafmDRaceurZy145EhVD%26response_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Fwww.facebook.com%252Foauth2%252Fredirect%252F%26scope%3Dopenid+email%26login_hint%3Dmelliaafifah15%2540gmail.com&amp;h=AT3tQoJYFz1w5uEbb8h4U_mbRCIiSBUC6v1YtgiMzFsqOtMEHLDqN3PvCq_rWuOKxuiotDh0VorXaHwGbE74R5QnlFtUrX1jD6DosFbA9ZV7nnXr4QTDWT68bJxfH-21T1WQwN2KbKC012wzv3O4MPAwSbayDgBITFw</value>
      <webElementGuid>057b3456-2a16-49df-b3f1-34c2793ad79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log In with Google</value>
      <webElementGuid>77d2786c-fba0-4460-8e4c-6e26dbf86d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginform&quot;)/div[4]/div[@class=&quot;_xkt&quot;]/a[@class=&quot;_42ft _4jy0 _82go _4jy6 _517h _51sy&quot;]</value>
      <webElementGuid>070bd859-decf-4ef8-8e32-7f701670d2de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginform']/div[4]/div/a</value>
      <webElementGuid>e1eb8674-5303-4d80-8249-5b66e108c9a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Log In with Google')]</value>
      <webElementGuid>a1a56e21-6d7d-408a-a821-7e11ed430c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log In'])[1]/following::a[1]</value>
      <webElementGuid>8bd6c5ab-eb4a-4813-8044-4cc4655cdef8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgotten password?'])[1]/following::a[1]</value>
      <webElementGuid>14cea36f-a2f3-45c5-9f70-2826634c4333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgotten password?'])[2]/preceding::a[1]</value>
      <webElementGuid>185313f8-8033-4601-a4e5-2a30c0bf2d7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English (UK)'])[1]/preceding::a[2]</value>
      <webElementGuid>cc26dcbc-4148-4162-be3c-83081a429011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log In with Google']/parent::*</value>
      <webElementGuid>b78ecef0-d921-44e0-91e6-0dec4c61796b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://accounts.google.com/o/oauth2/auth?client_id=15057814354-80cg059cn49j6kmhhkjam4b00on1gb2n.apps.googleusercontent.com&amp;state=ARe7JzeWUeTehscE4lSMv5KS0pcyExxSOnZN25xKSERrW8pN3swIy4ROGEpYGUgS2cnCIgTSQkz-mGV_yO5Rf63FtRqePo6X6M58uDmCJK1r8ClPhv_geqgLB9y_RbS-QN7AuhJ00QwDQlbg1jojqegE9aue62e3JI91zq4jAir781qlj6_hZDMYTeEQXc4hCWU9fUq-Fp5H-qpAW4ft8SDruDzZpNxfF0pX2Gx_oRpHIxBQlEUZFXyFpgB-bhCSAz7CoafmDRaceurZy145EhVD&amp;response_type=code&amp;redirect_uri=https%3A%2F%2Fwww.facebook.com%2Foauth2%2Fredirect%2F&amp;scope=openid+email&amp;login_hint=melliaafifah15%40gmail.com')]</value>
      <webElementGuid>4bbd9c88-ca66-415b-97c7-23884e0157d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>b0da1deb-d4d9-445b-bf4c-90c69a0ec77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://accounts.google.com/o/oauth2/auth?client_id=15057814354-80cg059cn49j6kmhhkjam4b00on1gb2n.apps.googleusercontent.com&amp;state=ARe7JzeWUeTehscE4lSMv5KS0pcyExxSOnZN25xKSERrW8pN3swIy4ROGEpYGUgS2cnCIgTSQkz-mGV_yO5Rf63FtRqePo6X6M58uDmCJK1r8ClPhv_geqgLB9y_RbS-QN7AuhJ00QwDQlbg1jojqegE9aue62e3JI91zq4jAir781qlj6_hZDMYTeEQXc4hCWU9fUq-Fp5H-qpAW4ft8SDruDzZpNxfF0pX2Gx_oRpHIxBQlEUZFXyFpgB-bhCSAz7CoafmDRaceurZy145EhVD&amp;response_type=code&amp;redirect_uri=https%3A%2F%2Fwww.facebook.com%2Foauth2%2Fredirect%2F&amp;scope=openid+email&amp;login_hint=melliaafifah15%40gmail.com' and (text() = 'Log In with Google' or . = 'Log In with Google')]</value>
      <webElementGuid>e06d122e-9329-498a-b0c4-06b346c351b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
