<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(We couldn, , t create your acc_8e27d1_1</name>
   <tag></tag>
   <elementGuidId>1b018680-78f5-4d51-b2e1-22e364a5cc2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='u_2_b_hQ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#u_2_b_hQ</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74682693-8c38-4315-ad0e-b7c8ca69faec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1edfa240-b053-4d47-9720-77c359325175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inputtext _58mg _5dba _2ph-</value>
      <webElementGuid>de7e5346-acb7-4241-91d6-348c181e3f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f600d9c2-3da4-489c-92b0-823f5f2676d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstname</value>
      <webElementGuid>cac5be92-279b-47de-bd07-1fc111da3219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>13a872e1-e667-4b20-b3fa-1fc0656b19d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>First name</value>
      <webElementGuid>a5aafc24-3c78-40bb-84bc-9ed0b9e9a13d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>u_2_b_hQ</value>
      <webElementGuid>e1913663-afef-453f-81ae-a22786ba15eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3a3f4234-055d-4efe-ab94-9a758ea620a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;u_2_b_hQ&quot;)</value>
      <webElementGuid>8c5c912e-5254-44ba-a1e2-775f0933d9f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='u_2_b_hQ']</value>
      <webElementGuid>332a59f3-8721-48d7-aad2-2d302425071b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='u_2_a_yz']/div/input</value>
      <webElementGuid>d1db473f-4f74-4de8-a110-a69eaeb8e19b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div/input</value>
      <webElementGuid>b8493220-d1e2-42d9-aa3d-28c29b7816e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'firstname' and @id = 'u_2_b_hQ']</value>
      <webElementGuid>75d15684-da07-43e7-9ea3-280446423b95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
