<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_123456789101112131415161718192021222_566da4</name>
   <tag></tag>
   <elementGuidId>9ef6b5a1-fe00-45ba-b240-dfc9a6178f3b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='day']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#day</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>977f943a-0190-4c40-84ce-0af1c10a73e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Day</value>
      <webElementGuid>af7515d6-8b71-4262-b42a-330bf614b3b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthday_day</value>
      <webElementGuid>a1d28a48-c795-4d38-a53d-740c1843b856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>day</value>
      <webElementGuid>149925cf-5d32-48df-8c22-4ab8098f8f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Day</value>
      <webElementGuid>28f94dae-3fbc-46dc-a6c1-2c858f591571</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_9407 _5dba _9hk6 _8esg</value>
      <webElementGuid>de54a395-3e2b-4ba2-8e24-8daaaf2d66df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12345678910111213141516171819202122232425262728293031</value>
      <webElementGuid>9e36c521-2eee-4ca3-930b-dec7d186c2ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;day&quot;)</value>
      <webElementGuid>20d1c0bf-7319-44bb-859b-d248c7e1f92b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='day']</value>
      <webElementGuid>410eeb25-1941-4b72-9bc4-e44c316ecc1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='u_2_l_be']/span/select</value>
      <webElementGuid>2f3703f7-dc49-439c-ade1-be9eab3e0315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date of birth'])[1]/following::select[1]</value>
      <webElementGuid>11105d59-fe0a-49fb-a187-e80feb1a87a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('We couldn', &quot;'&quot;, 't create your accountWe were not able to sign you up for Facebook.')])[1]/following::select[1]</value>
      <webElementGuid>15b76728-e9d3-4d6e-b6b2-eb595a9ea563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[1]/preceding::select[3]</value>
      <webElementGuid>9228f1d2-5e46-4556-9fdb-2a5ed1548f04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gender'])[1]/preceding::select[3]</value>
      <webElementGuid>3d737051-55eb-4978-bb5c-2e4b7aeef23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>36a80964-4d81-45b6-ba7d-5ad21e0b8289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'birthday_day' and @id = 'day' and @title = 'Day' and (text() = '12345678910111213141516171819202122232425262728293031' or . = '12345678910111213141516171819202122232425262728293031')]</value>
      <webElementGuid>b5cef426-ebf3-493e-b874-983cc9ecb856</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
