<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>445d1903-c147-470b-8cef-5bde8637857b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;reset_action&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='reset_action']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>776664aa-6855-4541-b4e4-8a18bca019c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5e8efc94-3db6-4303-a323-315f5f258886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_42ft _4jy0 _9nq0 textPadding20px _4jy3 _4jy1 selected _51sy</value>
      <webElementGuid>c4fd1d3a-d41a-4f92-80bb-b1a8ad225fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>reset_action</value>
      <webElementGuid>cd1a7b1b-78d7-4168-aec5-40bc7e07e21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>if ($(&quot;recover_openid&quot;).checked) {OpenIDConnectAuthentication.startAuth(&quot;https:\/\/accounts.google.com\/o\/oauth2\/auth?client_id=15057814354-80cg059cn49j6kmhhkjam4b00on1gb2n.apps.googleusercontent.com&amp;state=ARda-w_m2M9y2_dO4qTPsL9E2DUize-HZGZOx_hzIJyfx9-aWORbgSYDKlnfNLEmMVsfR78Qj2Jd4UX321_Ijt6Rl4j-LpIPIizjRc5hdxIgCEt3iw020uIPIBw-wbKx8pkA1dSasjPjYQ_Ts1P1qPiF1lF2WOoC3lD_ukm9IuV2Tf9EP0yRQBb5qUYMj6qHpUePbxbgwV66ApsALCU5213mSsuGWGx4zBpaTvfECm5BLbmC7XXBpOCa1lXmhht5pCiWOMSwJmGX1Fep4RhRleN_&amp;response_type=code&amp;redirect_uri=https\u00253A\u00252F\u00252Fwww.facebook.com\u00252Foauth2\u00252Fredirect\u00252F&amp;scope=openid+email&amp;login_hint=melliaafifah15\u002540gmail.com&quot;, &quot;account_recovery&quot;)}</value>
      <webElementGuid>03e3182f-5525-498d-87cb-502058e03b95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>33804f41-b438-4d95-9c2c-e3f86dfa2a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>33599a8b-cbf5-44ee-b0e6-2b04aac0d2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;initiate_interstitial&quot;)/div[@class=&quot;uiInterstitialBar uiBoxGray topborder&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;rfloat _ohf&quot;]/button[@class=&quot;_42ft _4jy0 _9nq0 textPadding20px _4jy3 _4jy1 selected _51sy&quot;]</value>
      <webElementGuid>8bbe872b-4626-4a31-9ea7-cf93ad14a5b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='reset_action']</value>
      <webElementGuid>c007a7dc-329e-4dc2-8c19-50c0bc83fc15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='initiate_interstitial']/div[3]/div/div/button</value>
      <webElementGuid>024d0d15-410b-4717-a8a2-7e44df6d2f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not you?'])[1]/following::button[1]</value>
      <webElementGuid>73cf417a-2414-4bda-8e44-e7e802b3fbbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Facebook user'])[1]/following::button[1]</value>
      <webElementGuid>8d8526c0-ff36-429d-96e2-328c28355432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No longer have access to these?'])[1]/preceding::button[1]</value>
      <webElementGuid>22ea9f84-4416-41bb-849d-8e1c81878526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English (UK)'])[1]/preceding::button[1]</value>
      <webElementGuid>4dbd1621-3ca3-4f0c-8150-94aa0a016352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>52c94b0c-c396-4710-ba09-bd65637db423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>3477fb0a-06d4-4727-9908-f279d999c8cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'reset_action' and @type = 'submit' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>7fe5edb1-83b8-4b7a-b9e5-e2c95d4bae58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
